// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://zypmdzehacooynvkqibz.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5cG1kemVoYWNvb3ludmtxaWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzQ5MzUsImV4cCI6MjA3MTcxMDkzNX0.ZwtljX9Vh2qQ8TZ9TiDtb6YW5B_VbtLLFQLVQ1uMfAk';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
